<Project Sdk="Aspire.AppHost.Sdk/13.3.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>3f608e36-56d4-4300-88b9-7a0ebfd95954</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="3.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ai-dev.mcp\ai-dev.mcp.csproj" />
    <ProjectReference Include="..\ai-dev.ui.winui\ai-dev.ui.winui.csproj" />
    <ProjectReference Include="..\ai-dev.api\ai-dev.api.csproj" />
  </ItemGroup>

</Project>
